spring:
  profiles:
    active: dev
    include: secret
  jpa:
    hibernate:
      ddl-auto: create
      jdbc:
        batch_size=50
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    root: INFO
    com.wanted.budget: DEBUG  #????
    org.hibernate.orm.jdbc.bind: TRACE # SQL ???? ???(?? ??? ?? ??)
    org.hibernate.orm.jdbc.extract: TRACE #??? ??? ???
